settings:
  hide: false
  content:
    merge: true

media:
    input: assets/images/posts
    output: /

content:
  - name: posts
    label: Articles
    type: collection
    path: _posts
    subfolders: true
    view:
      fields: [ guid, title, date, published ]
      primary: title
      sort: [ date ]
      default:
        sort: date
        order: desc

    # Schéma des champs pour les posts
    fields:

      - name: guid
        label: "Guid"
        type: number
        description: "Identifiant numérique unique (ex: 100, 101)"
        required: true
        
      - name: title
        label: "Titre"
        type: string
        required: true

      - name: slug
        label: "Slug"
        type: string
        description: "Identifiant utilisé dans l’URL"
        required: true

      - name: description
        label: "Description"
        type: string
        description: "Décris de façon précise l'article sert pour le référencement de 20 à 160 caractères"
        options:
          minlength: 20
          maxlength: 160
        required: true

      - name: layout
        label: "Calque"
        type: select
        required: true
        options:
          values: ['post']

      - name: ref
        label: "Ref"
        type: string
        description: "reference indexée par {{page.ref}} dans l'article"
        required: true

      - name: authors
        label: Auteurs
        type: select
        options:
          values:
            - value: Nico
              label: Nicolas Rodriguez
            - value: Math
              label: Mathieu Fogel
            - value: August
              label: Paul Bossut
            - value: Yann
              label: Yann Brochier
        required: true

      - name: date
        label: "Date de publication"
        type: date
        options:
          time: true
          format: yyyy-MM-dd HH:mm
        required: true

      - name: categories
        label: Categories
        type: select
        options:
          multiple: true
          values: 
            - value: Domotique
              label: Domotique
            - value: Haade-lab
              label: Haade-lab
            - value: Home-Assistant
              label: Home-Assistant
            - value: Zigbee
              label: Zigbee

      - name: published
        label: "Publié"
        type: boolean
        default: false
        
      - name: locale
        label: "Langue"
        type: select
        required: true
        options:
          values:
            - label: "Français"
              value: fr_FR
            - label: "English"
              value: en_GB

      - name: image
        label: "Image de couverture"
        type: image
        description: "Dimensions 1200x675px"

      - name: tags
        label: "Tags"
        type: string
        list: true
        description: "Mots-clés séparés"

      - name: rating
        label: "Note/Vote"
        type: number
        options:
          min: 0
          max: 5
          step: 0.1
        description: "vote article de 0.0 à 5.0"

      - name: sourcelink
        label: lien web externe
        type: select
        pattern:
          regex: '^(https?:\/\/)?(www\.)?[a-zA-Z0-9.-]+\.[a-zA-Z]{2,}(\/[^\s]*)?$'
          message: 'This must be a valid weblink address (e.g. https://haade.fr).'
        options:
          creatable: true
          multiple: true

      - name: body
        label: Contenu
        type: rich-text
        options:
          path: blog-images
          extensions: [jpg, jpeg, png]

components:
  hero: # 'hero' is the component name/key
    label: Hero Section
    type: object
    fields:
      - name: headline
        label: Headline
        type: text
        required: true
      - name: cover
        label: Cover Image
        type: image
  email: # 'email' is the component name/key
    label: Email Address
    type: string
    pattern:
      regex: '^[a-zA-Z0-9._%+-]+@[a-zA-Z0-9.-]+\.[a-zA-Z]{2,}$'
      message: 'This must be a valid email address (e.g. hello@example.com).'
