services:
  jekyll:
    build: .
    container_name: jekyll_site
    working_dir: /srv/jekyll
    command: bundle exec jekyll serve --host 0.0.0.0 --watch --force_polling --livereload
    ports:
      - "4000:4000"
    volumes:
      - .:/srv/jekyll
      - bundle_cache:/srv/jekyll/vendor/bundle
    environment:
      - JEKYLL_ENV=development

volumes:
  bundle_cache:




